project_id = "yaicfjdquvfifwtfpmbm"

[functions.send-invitation]
verify_jwt = false

[functions.validate-signup]
verify_jwt = false

[functions.seed-test-data]
verify_jwt = false

[functions.validate-join-code]
verify_jwt = false

[functions.assign-government-role]
verify_jwt = false