INSERT INTO public.articles (title, slug, category, excerpt, body, cover_image_url, author, published_date, is_featured, status)
VALUES (
  'New Kura Revolving Sushi Bar location opening in South Austin',
  'kura-revolving-sushi-south-austin',
  'grand_opening'::article_category,
  'Kura Revolving Sushi Bar opens its third Austin-area restaurant on Friday, June 10, 2026, in Sunset Valley, with $3.70 plates, a free t-shirt for the first 150 guests, and a chance to win Kura Sushi for a Year.',
  E'South Austin''s dining scene is about to get a jolt of conveyor-belt energy. Kura Revolving Sushi Bar, the tech-forward Japanese chain known for parading sushi past diners on a moving belt, is opening a new restaurant on Friday, June 10, in Sunset Valley, Texas, its third location in the greater Austin area.\n\n## Where and When\n\nThe new restaurant will take up residence at **5601 Brodie Lane, Suite 1400**, inside the Sunset Valley Village retail center, close to the intersection with Ernest Robles Way. It will be officially opening on **Friday, June 10, 2026**, marking Kura''s third Austin-area location.\n\nTo celebrate their grand opening, all sushi plates will be $3.70 and the first 150 guests will receive a free commemorative t-shirt. Kura Sushi Members who dine on June 10 to 12 will also be entered in a drawing for one of five "Kura Sushi for a Year" gift cards.\n\n## What to Expect\n\nKura''s calling card is its blend of nostalgia and technology. Dishes glide by on a conveyor belt beneath a patented ventilated lid that keeps plates fresh and lets a tracking system monitor how long each one has been circulating. Guests can grab what catches their eye or order directly from a tableside touchscreen.\n\nThe Sunset Valley menu is expected to mirror Kura''s typical offerings: classic nigiri and sashimi, hand rolls wrapped in either seaweed or rice paper, gunkan, and a rotating lineup of noodle dishes and soups. Standout proteins on the nigiri side include salmon and tuna alongside more adventurous picks like Hokkaido scallop, American Wagyu, conch, and eel. Noodle lovers can look forward to udon varieties such as beef and shrimp tempura udon, plus ramens like tantanmen and shoyu.\n\nA playful mascot named Mutenmaru also makes an appearance on tabletop screens, rewarding diners with small prizes for every 15 empty plates they deposit into the tracking slot as part of the brand''s effort to make sushi night feel like an interactive experience rather than just a meal.\n\n## A Growing Texas Footprint\n\nKura Sushi USA got its start in 2008 as a subsidiary of Japan''s Kura Sushi, Inc., a chain that traces its roots back to 1977 and has since expanded to more than 550 locations across Japan, Taiwan, and the United States. In Texas alone, the brand already operates in cities including San Antonio, Houston, Fort Worth, and Plano, with the Sunset Valley project marking its 18th Texas location once complete.\n\nFor now, fans of the revolving belt can sign up on Kura''s website to get the latest updates and score a $10 coupon in the process. Kura fans can also follow **@kurasushi_usa** on Instagram.',
  '/__l5e/assets-v1/130708e8-1748-43e3-b8d4-7c625ca5af05/kura-south-austin.png',
  'Go See The City',
  '2026-06-01T09:00:00Z',
  false,
  'published'
);