// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yaicfjdquvfifwtfpmbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhaWNmamRxdXZmaWZ3dGZwbWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzNDE0NjksImV4cCI6MjA4NzkxNzQ2OX0.UXqIl_oCqguuaEi-WEVkEJXJ1QDCDoEVQ5FmPqifhTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});